// =========================================================
// Auto-generated GF(2^10) Constant Multipliers by Alpha^(-i)
// Auto-generated by Python Script
// =========================================================

// --- Module 1: Multiplier by Alpha^(-1) (Dec: 516) ---
module gf_mul_const_alpha_inv1 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[1];
    assign p[1] = a[2];
    assign p[2] = a[0] ^ a[3];
    assign p[3] = a[4];
    assign p[4] = a[5];
    assign p[5] = a[6];
    assign p[6] = a[7];
    assign p[7] = a[8];
    assign p[8] = a[9];
    assign p[9] = a[0];
endmodule

// --- Module 2: Multiplier by Alpha^(-2) (Dec: 258) ---
module gf_mul_const_alpha_inv2 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[2];
    assign p[1] = a[0] ^ a[3];
    assign p[2] = a[1] ^ a[4];
    assign p[3] = a[5];
    assign p[4] = a[6];
    assign p[5] = a[7];
    assign p[6] = a[8];
    assign p[7] = a[9];
    assign p[8] = a[0];
    assign p[9] = a[1];
endmodule

// --- Module 3: Multiplier by Alpha^(-3) (Dec: 129) ---
module gf_mul_const_alpha_inv3 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[0] ^ a[3];
    assign p[1] = a[1] ^ a[4];
    assign p[2] = a[2] ^ a[5];
    assign p[3] = a[6];
    assign p[4] = a[7];
    assign p[5] = a[8];
    assign p[6] = a[9];
    assign p[7] = a[0];
    assign p[8] = a[1];
    assign p[9] = a[2];
endmodule

// --- Module 4: Multiplier by Alpha^(-4) (Dec: 580) ---
module gf_mul_const_alpha_inv4 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[1] ^ a[4];
    assign p[1] = a[2] ^ a[5];
    assign p[2] = a[0] ^ a[3] ^ a[6];
    assign p[3] = a[7];
    assign p[4] = a[8];
    assign p[5] = a[9];
    assign p[6] = a[0];
    assign p[7] = a[1];
    assign p[8] = a[2];
    assign p[9] = a[0] ^ a[3];
endmodule

// --- Module 5: Multiplier by Alpha^(-5) (Dec: 290) ---
module gf_mul_const_alpha_inv5 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[2] ^ a[5];
    assign p[1] = a[0] ^ a[3] ^ a[6];
    assign p[2] = a[1] ^ a[4] ^ a[7];
    assign p[3] = a[8];
    assign p[4] = a[9];
    assign p[5] = a[0];
    assign p[6] = a[1];
    assign p[7] = a[2];
    assign p[8] = a[0] ^ a[3];
    assign p[9] = a[1] ^ a[4];
endmodule

// --- Module 6: Multiplier by Alpha^(-6) (Dec: 145) ---
module gf_mul_const_alpha_inv6 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[0] ^ a[3] ^ a[6];
    assign p[1] = a[1] ^ a[4] ^ a[7];
    assign p[2] = a[2] ^ a[5] ^ a[8];
    assign p[3] = a[9];
    assign p[4] = a[0];
    assign p[5] = a[1];
    assign p[6] = a[2];
    assign p[7] = a[0] ^ a[3];
    assign p[8] = a[1] ^ a[4];
    assign p[9] = a[2] ^ a[5];
endmodule

// --- Module 7: Multiplier by Alpha^(-7) (Dec: 588) ---
module gf_mul_const_alpha_inv7 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[1] ^ a[4] ^ a[7];
    assign p[1] = a[2] ^ a[5] ^ a[8];
    assign p[2] = a[0] ^ a[3] ^ a[6] ^ a[9];
    assign p[3] = a[0];
    assign p[4] = a[1];
    assign p[5] = a[2];
    assign p[6] = a[0] ^ a[3];
    assign p[7] = a[1] ^ a[4];
    assign p[8] = a[2] ^ a[5];
    assign p[9] = a[0] ^ a[3] ^ a[6];
endmodule

// --- Module 8: Multiplier by Alpha^(-8) (Dec: 294) ---
module gf_mul_const_alpha_inv8 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[2] ^ a[5] ^ a[8];
    assign p[1] = a[0] ^ a[3] ^ a[6] ^ a[9];
    assign p[2] = a[0] ^ a[1] ^ a[4] ^ a[7];
    assign p[3] = a[1];
    assign p[4] = a[2];
    assign p[5] = a[0] ^ a[3];
    assign p[6] = a[1] ^ a[4];
    assign p[7] = a[2] ^ a[5];
    assign p[8] = a[0] ^ a[3] ^ a[6];
    assign p[9] = a[1] ^ a[4] ^ a[7];
endmodule

// --- Module 9: Multiplier by Alpha^(-9) (Dec: 147) ---
module gf_mul_const_alpha_inv9 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[0] ^ a[3] ^ a[6] ^ a[9];
    assign p[1] = a[0] ^ a[1] ^ a[4] ^ a[7];
    assign p[2] = a[1] ^ a[2] ^ a[5] ^ a[8];
    assign p[3] = a[2];
    assign p[4] = a[0] ^ a[3];
    assign p[5] = a[1] ^ a[4];
    assign p[6] = a[2] ^ a[5];
    assign p[7] = a[0] ^ a[3] ^ a[6];
    assign p[8] = a[1] ^ a[4] ^ a[7];
    assign p[9] = a[2] ^ a[5] ^ a[8];
endmodule

// --- Module 10: Multiplier by Alpha^(-10) (Dec: 589) ---
module gf_mul_const_alpha_inv10 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[0] ^ a[1] ^ a[4] ^ a[7];
    assign p[1] = a[1] ^ a[2] ^ a[5] ^ a[8];
    assign p[2] = a[0] ^ a[2] ^ a[3] ^ a[6] ^ a[9];
    assign p[3] = a[0] ^ a[3];
    assign p[4] = a[1] ^ a[4];
    assign p[5] = a[2] ^ a[5];
    assign p[6] = a[0] ^ a[3] ^ a[6];
    assign p[7] = a[1] ^ a[4] ^ a[7];
    assign p[8] = a[2] ^ a[5] ^ a[8];
    assign p[9] = a[0] ^ a[3] ^ a[6] ^ a[9];
endmodule

// --- Module 11: Multiplier by Alpha^(-11) (Dec: 802) ---
module gf_mul_const_alpha_inv11 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[1] ^ a[2] ^ a[5] ^ a[8];
    assign p[1] = a[0] ^ a[2] ^ a[3] ^ a[6] ^ a[9];
    assign p[2] = a[1] ^ a[3] ^ a[4] ^ a[7];
    assign p[3] = a[1] ^ a[4];
    assign p[4] = a[2] ^ a[5];
    assign p[5] = a[0] ^ a[3] ^ a[6];
    assign p[6] = a[1] ^ a[4] ^ a[7];
    assign p[7] = a[2] ^ a[5] ^ a[8];
    assign p[8] = a[0] ^ a[3] ^ a[6] ^ a[9];
    assign p[9] = a[0] ^ a[1] ^ a[4] ^ a[7];
endmodule

// --- Module 12: Multiplier by Alpha^(-12) (Dec: 401) ---
module gf_mul_const_alpha_inv12 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[0] ^ a[2] ^ a[3] ^ a[6] ^ a[9];
    assign p[1] = a[1] ^ a[3] ^ a[4] ^ a[7];
    assign p[2] = a[2] ^ a[4] ^ a[5] ^ a[8];
    assign p[3] = a[2] ^ a[5];
    assign p[4] = a[0] ^ a[3] ^ a[6];
    assign p[5] = a[1] ^ a[4] ^ a[7];
    assign p[6] = a[2] ^ a[5] ^ a[8];
    assign p[7] = a[0] ^ a[3] ^ a[6] ^ a[9];
    assign p[8] = a[0] ^ a[1] ^ a[4] ^ a[7];
    assign p[9] = a[1] ^ a[2] ^ a[5] ^ a[8];
endmodule

// --- Module 13: Multiplier by Alpha^(-13) (Dec: 716) ---
module gf_mul_const_alpha_inv13 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[1] ^ a[3] ^ a[4] ^ a[7];
    assign p[1] = a[2] ^ a[4] ^ a[5] ^ a[8];
    assign p[2] = a[0] ^ a[3] ^ a[5] ^ a[6] ^ a[9];
    assign p[3] = a[0] ^ a[3] ^ a[6];
    assign p[4] = a[1] ^ a[4] ^ a[7];
    assign p[5] = a[2] ^ a[5] ^ a[8];
    assign p[6] = a[0] ^ a[3] ^ a[6] ^ a[9];
    assign p[7] = a[0] ^ a[1] ^ a[4] ^ a[7];
    assign p[8] = a[1] ^ a[2] ^ a[5] ^ a[8];
    assign p[9] = a[0] ^ a[2] ^ a[3] ^ a[6] ^ a[9];
endmodule

// --- Module 14: Multiplier by Alpha^(-14) (Dec: 358) ---
module gf_mul_const_alpha_inv14 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[2] ^ a[4] ^ a[5] ^ a[8];
    assign p[1] = a[0] ^ a[3] ^ a[5] ^ a[6] ^ a[9];
    assign p[2] = a[0] ^ a[1] ^ a[4] ^ a[6] ^ a[7];
    assign p[3] = a[1] ^ a[4] ^ a[7];
    assign p[4] = a[2] ^ a[5] ^ a[8];
    assign p[5] = a[0] ^ a[3] ^ a[6] ^ a[9];
    assign p[6] = a[0] ^ a[1] ^ a[4] ^ a[7];
    assign p[7] = a[1] ^ a[2] ^ a[5] ^ a[8];
    assign p[8] = a[0] ^ a[2] ^ a[3] ^ a[6] ^ a[9];
    assign p[9] = a[1] ^ a[3] ^ a[4] ^ a[7];
endmodule

// --- Module 15: Multiplier by Alpha^(-15) (Dec: 179) ---
module gf_mul_const_alpha_inv15 (
    input  logic [9:0] a,
    output logic [9:0] p
);
    assign p[0] = a[0] ^ a[3] ^ a[5] ^ a[6] ^ a[9];
    assign p[1] = a[0] ^ a[1] ^ a[4] ^ a[6] ^ a[7];
    assign p[2] = a[1] ^ a[2] ^ a[5] ^ a[7] ^ a[8];
    assign p[3] = a[2] ^ a[5] ^ a[8];
    assign p[4] = a[0] ^ a[3] ^ a[6] ^ a[9];
    assign p[5] = a[0] ^ a[1] ^ a[4] ^ a[7];
    assign p[6] = a[1] ^ a[2] ^ a[5] ^ a[8];
    assign p[7] = a[0] ^ a[2] ^ a[3] ^ a[6] ^ a[9];
    assign p[8] = a[1] ^ a[3] ^ a[4] ^ a[7];
    assign p[9] = a[2] ^ a[4] ^ a[5] ^ a[8];
endmodule
